### ISSUE TITLE
Line 3295: Syntax Error unexpected file end

### ISSUE THREAD

**Issue by k0b4** [Screetsec/LALIN#4]
Please check the end of the script.
There is also a problem is a quotation marks before "Back to Main" -->
select lalinselc in "Install Google Chrome" "Install Chromium" "Install Firefox" "Install Min" "Install TOR-32bit" **"Install Tor-64bit"Back to Main"**; do

Greetz Koba

**Comment by screetsec** [comment]
will be check

**Comment by screetsec** [comment]
done
